### ISSUE TITLE
JSONFormatter for Enabled on Navigator is incorrect

### ISSUE THREAD

**Issue by foxyfoxza** [lisa3907/dotnet.highstock#1]
should be: 

 /// <summary>

        /// Enable or disable the navigator. 
        /// Defaults to true.
        /// </summary>

        [JsonFormatter("{{ 0 }}")]
        public bool? Enabled
        {
            get;
            set;
        }

**Comment by lisa3907** [comment]
Thanks for pointing this out! We'll push a fix for this today.

**Comment by lisa3907** [comment]
Thanks for pointing this out! We'll push a fix for this today.
