### ISSUE TITLE
Disabled Navigator

### ISSUE THREAD

**Issue by beedjees** [lisa3907/dotnet.highstock#3]
When we disabled the Navigator, the output ScriptHtmlString is not correctly generated.

Here is c# code :
`chart.SetNavigator(new Navigator { Enabled = false });`

Here is JS result from @chart.ChartScriptHtmlString()
`navigator: { enabled: { 0 } }`

Here is the JS which should be generated
`navigator: { enabled: false }`

**Comment by weedkiller** [comment]
Can you update to asp 5.0 core

**Comment by lisa3907** [comment]
updated to core 5.0
